# Generated by Django 5.1.6 on 2026-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='ai_description',
            field=models.TextField(blank=True, default='', help_text="Additional AI instructions (e.g., 'Help me impress my teacher and get high grades')"),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='ai_persona',
            field=models.TextField(blank=True, default='You are a helpful tutor', help_text="AI persona/role (e.g., 'You are a grade 3 student')"),
        ),
    ]
