# Generated by Django 5.1.6 on 2026-03-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_transcriptchunk_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source_type',
            field=models.CharField(choices=[('recitation', 'Recitation (Live Capture)'), ('lesson', 'Lesson (Document Upload)')], db_index=True, default='recitation', max_length=20),
        ),
        migrations.AddField(
            model_name='transcriptchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
