# Generated by Django 5.1.6 on 2026-03-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_edited_at_transcriptchunk_edited_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lesson',
            new_name='lessons_les_user_id_551c8b_idx',
            old_name='lessons_les_user_id_source_created_idx',
        ),
    ]
